name: env_post_processing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.9.2
  - xlsxwriter=3.1.1
  - ipykernel=6.29.5
  - seaborn
  - boto3
  - rpy2
  - pip
  - PyYAML
  - pip:
      - costs-benefits-ssp