name: ssp_uganda_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.9.2
  - xlsxwriter=3.1.1
  - ipykernel=6.29.5
  - seaborn
  - pip
  - pip:
      - git+https://github.com/jcsyme/sisepuede/
      - ssp-transformations-handler