"""
Surrogate Model Predictor Service
===================================
Loads the trained XGBoost sector pipeline and provides a clean interface for
running simulations. All knowledge about the model's expected input format
is encapsulated here — the rest of the application does not need to know
about column ordering, feature names, or units.

A single model serves everything: the sector pipeline outputs 59 targets —
the 11 aggregate metrics (emissions/costs/co-benefits) AND the 48 sector×year
emission values. There is no separate "aggregate" model.

Key design decisions:
  - Feature order is read from the model itself (`feature_names_in_`) and the
    model is fed a NAMED pandas DataFrame, so XGBoost aligns features by name.
    Passing a bare NumPy array would align positionally and silently scramble
    inputs if the column order ever differs.
  - Target column order + the aggregate-metric training distributions (used for
    percentile-in-training) come from backend/target_distributions.json, a small
    sidecar generated by scripts/build_target_distributions.py. The training
    parquet is NOT loaded at runtime.
  - Defaults (L=0.1 for BAU, X=-1.0 for BAU) are applied for any group not
    explicitly overridden by the caller.

To update the model:
  1. Retrain the sector XGBoost pipeline.
  2. Update MODEL_SECTOR_PATH in config.py (or .env).
  3. Re-run `python -m backend.scripts.build_target_distributions`.
  4. Restart the server — this module will pick up the new files automatically.
"""

import json
import logging

import joblib
import numpy as np
import pandas as pd
from scipy import stats

from backend.config import settings

logger = logging.getLogger(__name__)

# ── Output metric metadata (units, display names) ────────────────────────────
# Kept here (not only in the registry) because the predictor needs units to
# build PredictionResult objects without importing the full registry.

# The 3 emission aggregates are still dedicated model targets with a training
# distribution (for percentile-in-training). Cost/benefit are no longer aggregate
# targets — they come disaggregated by year × type (see COST_BENEFIT_* below) and
# the headline cost/benefit numbers are derived per-year totals.
TARGET_METADATA: dict[str, dict] = {
    "emission_total_sum": {
        "display_name": "Total Cumulative Emissions (2025–2070)",
        "unit": "Mt CO₂e",
    },
    "2033_2037_mean_emission": {
        "display_name": "Near-Term Annual Emissions (2033–2037 avg)",
        "unit": "Mt CO₂e/yr",
    },
    "2066_2070_mean_emission": {
        "display_name": "Long-Term Annual Emissions (2066–2070 avg)",
        "unit": "Mt CO₂e/yr",
    },
}

# Years the disaggregated cost/benefit targets are reported for.
COST_BENEFIT_YEARS: list[int] = [2030, 2040, 2050, 2070]

# Display labels for the raw cost/benefit type codes (column suffixes).
COST_BENEFIT_LABELS: dict[str, str] = {
    # benefits (positive)
    "air_pollution": "Air Quality",
    "human_health": "Human Health",
    "congestion": "Reduced Congestion",
    "road_safety": "Road Safety",
    "consumer_savings": "Consumer Savings",
    "technical_savings": "Technical Savings",
    "crop_value": "Crop Value",
    "lvst_value": "Livestock Value",
    "ippu_value": "Industrial Value",
    "ecosystem_services": "Ecosystem Services",
    "env_pollution": "Environmental Pollution",
    "land_pollution": "Land Pollution",
    "water_pollution": "Water Pollution",
    "sector_specific": "Sector-Specific",
    # costs (negative)
    "technical": "Technical Cost",
    "system": "System Cost",
    "fuel": "Fuel Cost",
}

# Defaults applied when a group is not overridden by the caller.
# L features: 0.1 = minimal policy (BAU baseline)
# X features: -1.0 = fixed baseline trajectory (no uncertainty variation)
BAU_L_DEFAULT: float = 0.1
BAU_X_DEFAULT: float = -1.0

MODERATE_L_DEFAULT: float = 0.5
MODERATE_X_DEFAULT: float = 0.5

# Groups not in the NZ strategy stay at BAU (0.1).
NETZERO_L_DEFAULT: float = 0.1
NETZERO_X_DEFAULT: float = 0.5

# Per-group L values derived from the NZ strategy YAML files.
# Formula: T = NZ_magnitude / transformer_default; L = (T - 0.1) / 0.9, clamped [0,1].
# Groups absent from the NZ strategy (22, 29, 5) remain at BAU = 0.1.
NETZERO_L_OVERRIDES: dict[int, float] = {
    1:  1.0,     # Rice Paddy Methane Reduction
    2:  1.0,     # Agricultural Food Loss Reduction
    3:  1.0,     # Conservation Agriculture
    4:  1.0,     # Crop Yield Improvement
    5:  0.1,     # CCS — NZ uses only 1% of default capacity
    6:  1.0,     # Electricity Grid Efficiency
    7:  1.0,     # Clean Hydrogen
    8:  1.0,     # Renewable Electricity Target
    9:  1.0,     # Fugitive Gas Leak Reduction
    10: 1.0,     # Methane Flaring
    11: 1.0,     # Forest Carbon Sequestration
    12: 1.0,     # Industrial Fuel Efficiency
    13: 1.0,     # Industrial Production Efficiency
    14: 1.0,     # Industrial Fuel Mix Shift
    15: 1.0,     # Low-Clinker Cement
    16: 1.0,     # Industrial Production Demand Reduction
    17: 1.0,     # Industrial N₂O Process Emissions
    18: 1.0,     # Industrial PFC Emissions
    19: 1.0,     # Deforestation Reduction
    20: 1.0,     # Wetland Protection
    21: 1.0,     # Reforestation
    22: 0.1,     # Silvopasture — not in NZ strategy
    23: 1.0,     # Livestock Manure Biogas Capture
    24: 0.9942,  # Cattle & Pig Manure Management
    25: 0.9942,  # Other Livestock Manure Management
    26: 0.9942,  # Poultry Manure Management
    27: 1.0,     # Livestock Enteric Fermentation
    28: 1.0,     # Livestock Productivity
    29: 0.1,     # Diet Shift — not in NZ strategy
    30: 1.0,     # Industrial CO₂ Capture
    31: 0.7778,  # Building Heat Demand Reduction
    32: 0.5556,  # Building Appliance Efficiency
    33: 1.0,     # Biomass Cooking Stove Efficiency
    34: 0.9415,  # Building Fuel Mix Shift
    35: 1.0,     # Agricultural Liming Reduction
    36: 1.0,     # Nitrogen Fertilizer Reduction
    37: 1.0,     # Transport Demand Reduction
    38: 1.0,     # Electric Vehicle Efficiency
    39: 1.0,     # Non-Electric Vehicle Efficiency
    40: 1.0,     # Passenger Vehicle Occupancy
    41: 1.0,     # Light Duty Vehicle Electrification
    42: 0.6825,  # Maritime Fuel Shift
    43: 1.0,     # Medium Duty Vehicle Electrification
    44: 1.0,     # Rail Electrification
    45: 1.0,     # Freight Mode Shift
    46: 1.0,     # Passenger Mode Shift
    47: 1.0,     # Regional Transport Mode Shift
    48: 1.0,     # Wastewater Biogas Capture
    49: 1.0,     # Septic System Compliance
    50: 1.0,     # Industrial Wastewater Treatment
    51: 1.0,     # Rural Wastewater Treatment
    52: 1.0,     # Urban Wastewater Treatment
    53: 1.0,     # Consumer Food Waste Reduction
    54: 1.0,     # Organic Waste Composting
    55: 1.0,     # Landfill Gas Capture
    56: 1.0,     # Landfill Gas Energy Recovery
    57: 1.0,     # Waste Incineration Energy Recovery
    58: 1.0,     # Controlled Landfilling
    59: 1.0,     # Solid Waste Recycling
}

PRESET_DEFAULTS = {
    "bau":      (BAU_L_DEFAULT, BAU_X_DEFAULT),
    "moderate": (MODERATE_L_DEFAULT, MODERATE_X_DEFAULT),
    "netzero":  (NETZERO_L_DEFAULT, NETZERO_X_DEFAULT),
}


# ── Sector metadata ───────────────────────────────────────────────────────────

SECTOR_DISPLAY_NAMES: dict[str, str] = {
    "agrc": "Agriculture",
    "frst": "Forestry (Carbon Sequestration)",
    "inen": "Industrial Energy",
    "ippu": "Industrial Processes",
    "lndu": "Land Use",
    "lsmm": "Livestock Manure Management",
    "lvst": "Livestock",
    "scoe": "Stationary Combustion (Cooking & Buildings)",
    "soil": "Soil Emissions",
    "trns": "Transportation",
    "trww": "Wastewater Treatment",
    "waso": "Solid Waste",
}

_SECTOR_CODES = list(SECTOR_DISPLAY_NAMES.keys())
_EMISSIONS_2019_CACHE: dict[str, float] | None = None


def _load_sector_emissions_2019() -> dict[str, float]:
    """Return per-sector MtCO2e for 2019 from the BAU-nearest S3 baseline run.

    Finds the LHS trial closest to BAU (all L=0.1, design_id=3) and reads
    time_period=4 (year 2019 = 2015 + 4) from the S3 model_outputs.
    Result is cached at module level.
    """
    global _EMISSIONS_2019_CACHE
    if _EMISSIONS_2019_CACHE is not None:
        return _EMISSIONS_2019_CACHE

    from backend.services.s3_lookup import find_nearest_lhs_trial, get_model_outputs_row

    bau_l_values = {gid: BAU_L_DEFAULT for gid in range(1, 60)}
    primary_id = find_nearest_lhs_trial(bau_l_values, design_id=3)
    outputs = get_model_outputs_row(primary_id)  # {col: [val_tp0, ..., val_tp55]}

    _EMISSIONS_2019_CACHE = {}
    for s in _SECTOR_CODES:
        col = f"emission_co2e_subsector_total_{s}"
        values = outputs.get(col, [])
        _EMISSIONS_2019_CACHE[s] = round(float(values[4]), 3) if len(values) > 4 else 0.0

    logger.info("Loaded 2019 sector baseline from S3 (primary_id=%d)", primary_id)
    return _EMISSIONS_2019_CACHE


class SectorPredictor:
    """
    Sole surrogate predictor, backed by the multi-output XGBoost pipeline that
    outputs 123 targets: 3 emission aggregates, 12 sectors × 4 years of emissions,
    and cost/benefit disaggregated by type × year (14 benefit + 3 cost types) plus
    per-year GDP — all for 2030/2040/2050/2070.

    Usage
    -----
    predictor = SectorPredictor()
    result = predictor.predict(lever_overrides={8: 0.9, 33: 0.8})
    result["predictions"]["emission_total_sum"]["value"]   # emission aggregate
    result["sector_trajectories"]["scoe"]                  # {2030: 45.2, ...}
    result["cost_benefit"][2050]["total_benefit"]          # per-year totals + %GDP
    """

    def __init__(self) -> None:
        self._model = self._load_model()
        (
            self._feature_columns,
            self._group_to_column,
            self._target_columns,
            self._target_distributions,
            self._target_index,
            self._registry,
        ) = self._load_metadata()
        logger.info(
            "SectorPredictor ready. Features: %d, Targets: %d (aggregate: %d)",
            len(self._feature_columns),
            len(self._target_columns),
            len(TARGET_METADATA),
        )

    # ── Public interface ────────────────────────────────────────────────────

    def predict(
        self,
        lever_overrides: dict[int, float] | None = None,
        exogenous_overrides: dict[int, float] | None = None,
        preset_scenario: str = "bau",
        scenario_name: str = "Scenario",
    ) -> dict:
        """
        Run the surrogate model for one scenario.

        Returns a dict with:
            scenario_name        (str)
            feature_vector       (dict[str, float])  column_name → value used
            group_values         (dict[int, float])  group_id → value used
            predictions          (dict[str, dict])   3 emission aggregate metrics
            sector_trajectories  (dict[str, dict[int, float]])  sector → {year: MtCO2e}
            cost_benefit         (dict[int, dict])   year → {benefits, costs, gdp,
                                 total_benefit, total_cost, net, cost_pct_gdp,
                                 benefit_pct_gdp}. Benefits positive, costs negative.
        """
        lever_overrides = lever_overrides or {}
        exogenous_overrides = exogenous_overrides or {}

        l_default, x_default = PRESET_DEFAULTS.get(preset_scenario, (BAU_L_DEFAULT, BAU_X_DEFAULT))

        # For netzero, seed lever values from per-group NZ overrides, then let
        # caller's explicit lever_overrides take priority on top.
        if preset_scenario == "netzero":
            lever_overrides = {**NETZERO_L_OVERRIDES, **lever_overrides}

        group_values = self._build_group_values(lever_overrides, exogenous_overrides, l_default, x_default)
        feature_vector = self._build_feature_vector(group_values)

        # Named DataFrame → the pipeline aligns features by name (NOT position).
        X = pd.DataFrame([feature_vector])[self._feature_columns]
        raw_predictions = self._model.predict(X)[0]  # shape: (n_targets,)

        # Aggregate emission metrics (3) — indexed by target-column name.
        predictions = {}
        for target_name in TARGET_METADATA:
            value = float(raw_predictions[self._target_index[target_name]])
            dist = self._target_distributions.get(target_name, {})
            vals = dist.get("values") or [value]
            predictions[target_name] = {
                "value": round(value, 4),
                "unit": TARGET_METADATA[target_name]["unit"],
                "display_name": TARGET_METADATA[target_name]["display_name"],
                "training_range": dist.get("range", {"min": 0, "max": 0}),
                "percentile_in_training": round(
                    float(stats.percentileofscore(vals, value)), 1
                ),
            }

        # Sector × year trajectories AND disaggregated cost/benefit (+ GDP).
        sector_trajectories: dict[str, dict[int, float]] = {}
        cost_benefit: dict[int, dict] = {}
        for i, col in enumerate(self._target_columns):
            val = float(raw_predictions[i])
            if col.startswith("emission_") and "_yr" in col:
                sector, year_str = col.replace("emission_", "", 1).split("_yr")
                sector_trajectories.setdefault(sector, {})[int(year_str)] = round(val, 3)
            elif col.startswith("benefit_"):
                typ, yr = col[len("benefit_"):].rsplit("_yr", 1)
                cost_benefit.setdefault(int(yr), {}).setdefault("benefits", {})[typ] = round(val, 4)
            elif col.startswith("cost_"):
                typ, yr = col[len("cost_"):].rsplit("_yr", 1)
                cost_benefit.setdefault(int(yr), {}).setdefault("costs", {})[typ] = round(val, 4)
            elif col.startswith("gdp_mmm_usd_yr"):
                yr = col[len("gdp_mmm_usd_yr"):]
                cost_benefit.setdefault(int(yr), {})["gdp"] = round(val, 4)

        # Per-year totals + cost/benefit as % of GDP (benefits +, costs −).
        for yr, d in cost_benefit.items():
            total_b = sum(d.get("benefits", {}).values())
            total_c = sum(d.get("costs", {}).values())
            gdp = d.get("gdp") or 0.0
            d["total_benefit"] = round(total_b, 4)
            d["total_cost"] = round(total_c, 4)
            d["net"] = round(total_b + total_c, 4)
            d["cost_pct_gdp"] = round(100 * abs(total_c) / gdp, 4) if gdp else 0.0
            d["benefit_pct_gdp"] = round(100 * total_b / gdp, 4) if gdp else 0.0

        return {
            "scenario_name": scenario_name,
            "feature_vector": feature_vector,
            "group_values": group_values,
            "predictions": predictions,
            "sector_trajectories": sector_trajectories,
            "cost_benefit": cost_benefit,
        }

    def predict_comparison(
        self,
        lever_overrides: dict[int, float] | None = None,
        exogenous_overrides: dict[int, float] | None = None,
        preset_scenario: str = "bau",
        scenario_name: str = "Scenario",
    ) -> dict:
        """
        Run the scenario AND a BAU baseline. Returns both plus:
          - comparison          : % change vs BAU for the 3 emission aggregates
          - sector_deltas       : per sector × year absolute and % deltas vs BAU
          - cost_benefit_deltas : per year, scenario vs BAU totals + cost %-GDP
        """
        scenario = self.predict(lever_overrides, exogenous_overrides, preset_scenario, scenario_name)
        baseline = self.predict({}, {}, "bau", "Business as Usual (Baseline)")

        # Aggregate % change vs BAU.
        comparison: dict[str, float] = {}
        for metric in TARGET_METADATA:
            scenario_val = scenario["predictions"][metric]["value"]
            baseline_val = baseline["predictions"][metric]["value"]
            comparison[metric] = (
                round(100 * (scenario_val - baseline_val) / abs(baseline_val), 2)
                if baseline_val != 0
                else 0.0
            )

        # Anchor both trajectories at the 2019 historical baseline (pre-policy
        # divergence). Non-fatal: an S3 hiccup just omits the 2019 anchor point.
        try:
            emissions_2019 = _load_sector_emissions_2019()
            for sector, val in emissions_2019.items():
                scenario["sector_trajectories"].setdefault(sector, {})[2019] = val
                baseline["sector_trajectories"].setdefault(sector, {})[2019] = val
        except Exception as exc:
            logger.warning("Could not load 2019 sector baseline (non-fatal): %s", exc)

        sector_deltas: dict[str, dict[int, dict]] = {}
        for sector, traj in scenario["sector_trajectories"].items():
            sector_deltas[sector] = {}
            for year, val in traj.items():
                bau_val = baseline["sector_trajectories"].get(sector, {}).get(year, 0.0)
                abs_delta = round(val - bau_val, 3)
                pct_delta = round(100 * (val - bau_val) / abs(bau_val), 2) if bau_val != 0 else 0.0
                sector_deltas[sector][year] = {
                    "scenario": val,
                    "bau": round(bau_val, 3),
                    "delta": abs_delta,
                    "pct_change": pct_delta,
                }

        # Per-year cost/benefit: scenario vs BAU totals + cost-as-%-of-GDP.
        cost_benefit_deltas: dict[int, dict] = {}
        for year in COST_BENEFIT_YEARS:
            s = scenario["cost_benefit"].get(year, {})
            b = baseline["cost_benefit"].get(year, {})
            cost_benefit_deltas[year] = {
                "benefit_scenario": s.get("total_benefit", 0.0),
                "benefit_bau": b.get("total_benefit", 0.0),
                "cost_scenario": s.get("total_cost", 0.0),
                "cost_bau": b.get("total_cost", 0.0),
                "net_scenario": s.get("net", 0.0),
                "net_bau": b.get("net", 0.0),
                "cost_pct_gdp_scenario": s.get("cost_pct_gdp", 0.0),
                "cost_pct_gdp_bau": b.get("cost_pct_gdp", 0.0),
            }

        return {
            "scenario": scenario,
            "baseline": baseline,
            "comparison": comparison,
            "sector_deltas": sector_deltas,
            "cost_benefit_deltas": cost_benefit_deltas,
        }

    def get_feature_info(self) -> dict:
        """Return the full feature registry (for /api/features endpoint)."""
        return self._registry

    def get_group_to_column(self) -> dict[int, str]:
        """Map group_id → training column name."""
        return self._group_to_column

    def get_sector_display_name(self, sector: str) -> str:
        return SECTOR_DISPLAY_NAMES.get(sector, sector.upper())

    # ── Private helpers ─────────────────────────────────────────────────────

    def _load_model(self):
        path = settings.model_sector_path
        if not path.exists():
            raise FileNotFoundError(
                f"Sector model not found at {path}. "
                "Update MODEL_SECTOR_PATH in config.py or .env."
            )
        model = joblib.load(path)
        logger.info("Loaded sector model from %s", path)
        return model

    def _load_metadata(self):
        """
        Assemble everything the predictor needs WITHOUT loading the training
        parquet:
          - feature column order    → from the model's `feature_names_in_`
          - target column order     → from the sidecar JSON
          - aggregate distributions → from the sidecar JSON (percentile + range)
          - group_id → column map   → from the feature registry
        """
        # Feature order straight from the trained model — guarantees the
        # DataFrame we build matches what the model expects.
        feature_columns = [str(c) for c in self._model.feature_names_in_]

        # Target column order + aggregate distributions from the sidecar.
        path = settings.target_distributions_path
        if not path.exists():
            raise FileNotFoundError(
                f"Target distributions sidecar not found at {path}. "
                "Run: python -m backend.scripts.build_target_distributions"
            )
        with open(path) as f:
            sidecar = json.load(f)
        target_columns = sidecar["target_columns"]
        target_distributions = sidecar["target_distributions"]
        target_index = {name: target_columns.index(name) for name in TARGET_METADATA}

        # group_id → column name map from the registry.
        with open(settings.feature_registry_path) as f:
            registry = json.load(f)
        group_to_column: dict[int, str] = {}
        for gid, meta in {**registry["lever_features"], **registry["exogenous_features"]}.items():
            group_to_column[int(gid)] = meta["training_column"]

        logger.info(
            "Metadata loaded. Features: %d, Targets: %d", len(feature_columns), len(target_columns)
        )
        return feature_columns, group_to_column, target_columns, target_distributions, target_index, registry

    def _build_group_values(
        self,
        lever_overrides: dict[int, float],
        exogenous_overrides: dict[int, float],
        l_default: float,
        x_default: float,
    ) -> dict[int, float]:
        """
        Build a complete {group_id: value} dict for all 68 groups.
        Overrides take priority; everything else gets the default.
        Values are clamped to their valid ranges.
        """
        group_values: dict[int, float] = {}
        # L features: groups 1–59
        for gid in range(1, 60):
            group_values[gid] = float(np.clip(lever_overrides.get(gid, l_default), 0.0, 1.0))
        # X features: groups 60–68
        for gid in range(60, 69):
            group_values[gid] = float(np.clip(exogenous_overrides.get(gid, x_default), -1.0, 1.0))
        return group_values

    def _build_feature_vector(self, group_values: dict[int, float]) -> dict[str, float]:
        """
        Convert {group_id: value} to {column_name: value} for every feature
        column the model expects. Order does not matter here — predict() selects
        columns by name into the model's `feature_names_in_` order.

        Any column not mapped by the registry falls back to its training median.
        This should not happen in normal operation but prevents silent failures
        if the registry ever gets out of sync with the model.
        """
        vector: dict[str, float] = {}
        for col in self._feature_columns:
            matched_gid = next(
                (gid for gid, col_name in self._group_to_column.items() if col_name == col),
                None,
            )
            if matched_gid is not None and matched_gid in group_values:
                vector[col] = group_values[matched_gid]
            else:
                logger.warning("Column %s has no registry mapping — using fallback", col)
                vector[col] = 0.5 if "_L_" in col else 0.0
        return vector


# ── Module-level singleton ──────────────────────────────────────────────────
# Instantiated once (lazily) so the model is loaded once at startup. The FastAPI
# app pre-warms it in its startup event to avoid cold-start latency.

_sector_predictor: SectorPredictor | None = None


def get_sector_predictor() -> SectorPredictor:
    """Return the module-level sector predictor singleton (lazy-initialised)."""
    global _sector_predictor
    if _sector_predictor is None:
        _sector_predictor = SectorPredictor()
    return _sector_predictor
