"""
Sector crosswalk (official inventory categories)
================================================
Single source of truth for the 23 official inventory sector categories the app
displays. Loads `backend/sector_categories.json` (generated by the training
pipeline's `athena/gen_emissions_sql.py` from the team's crosswalk) and exposes:

  - CATEGORIES     : slugs in the team's legend order
  - DISPLAY/SHORT/COLOR/LULUCF : per-slug presentation + LULUCF flag
  - SECTOR_META    : {slug: {label, short, color}} for the frontend (delivered via
                     the result bundle's `sector_meta_overrides`, merged over the
                     frontend's own SECTOR_META)
  - categories_from_fields(get) : sum the granular `emission_co2e_*` fields into the
                     23 categories, given a getter that returns a field's value.

Why this exists: the surrogate now TRAINS on these categories, but the real
pathways (uganda_pathways.csv) and the 2019 baseline still arrive as granular
fields. This module re-aggregates them the SAME way the training extract did, so
every surface — surrogate, real pathways, baseline — speaks one language.
"""

import json
from pathlib import Path

_SIDECAR = Path(__file__).parent.parent / "sector_categories.json"

with open(_SIDECAR) as _f:
    _META: dict = json.load(_f)

# Slugs in the team's legend / stacking order.
CATEGORIES: list[str] = sorted(_META, key=lambda s: _META[s]["order"])

DISPLAY: dict[str, str] = {s: _META[s]["display"] for s in CATEGORIES}
SHORT: dict[str, str] = {s: _META[s]["short"] for s in CATEGORIES}
COLOR: dict[str, str] = {s: _META[s]["color"] for s in CATEGORIES}
LULUCF: dict[str, bool] = {s: bool(_META[s]["lulucf"]) for s in CATEGORIES}
_FIELDS: dict[str, list[str]] = {s: _META[s]["fields"] for s in CATEGORIES}

# Ready-to-merge presentation for the frontend (label + short + colour per slug).
SECTOR_META: dict[str, dict] = {
    s: {"label": DISPLAY[s], "short": SHORT[s], "color": COLOR[s], "order": _META[s]["order"]}
    for s in CATEGORIES
}


def categories_from_fields(get) -> dict[str, float]:
    """Re-aggregate granular emissions into the 23 categories.

    `get(field_name)` must return the field's value (0.0 if absent) — e.g.
    `row.get` for a dict, or a small closure over a pandas Series. Mirrors the
    training SQL exactly: each category is the sum of COALESCE(field, 0).
    """
    out: dict[str, float] = {}
    for slug in CATEGORIES:
        total = 0.0
        for field in _FIELDS[slug]:
            v = get(field)
            if v is None:
                continue
            v = float(v)
            if v != v:          # NaN — treat as 0, matching the SQL's COALESCE(...,0)
                continue
            total += v
        out[slug] = total
    return out
